import { RoleScope } from "@prisma/client";

export type PermissionDefinition = {
  key: string;
  module: string;
  action: string;
  description: string;
};

export type NavigationSeedItem = {
  key: string;
  label: string;
  href: string;
  sortOrder: number;
  permissionKey: string;
  isActive?: boolean;
};

export type RoleSeedDefinition = {
  key: string;
  name: string;
  description: string;
  scope: RoleScope;
  level: number;
  isSystem: boolean;
};

export type SettingSeedDefinition = {
  key: string;
  value: Record<string, unknown>;
  isSecret: boolean;
};

const staticPermissions: PermissionDefinition[] = [
  { key: "dashboard.read", module: "dashboard", action: "read", description: "Access dashboard." },
  { key: "dashboard.platform", module: "dashboard", action: "platform", description: "View platform-level dashboard." },
  { key: "dashboard.company", module: "dashboard", action: "company", description: "View company-level dashboard." },
  { key: "platform.dashboard", module: "platform", action: "dashboard", description: "View platform admin dashboard." },
  { key: "platform.manage", module: "platform", action: "manage", description: "Manage platform-level entities." },
  { key: "settings.read", module: "settings", action: "read", description: "Read settings." },
  { key: "settings.update", module: "settings", action: "update", description: "Update settings." },
  { key: "profile.email_change.request", module: "profile", action: "email_change.request", description: "Request an email change for the signed-in user." },
  { key: "audit_logs.read", module: "audit_logs", action: "read", description: "Read audit logs." },
  { key: "inventory.read", module: "inventory", action: "read", description: "Read inventory management module." },
  { key: "inventory.manage", module: "inventory", action: "manage", description: "Manage inventory management module." },
  { key: "suppliers.read", module: "suppliers", action: "read", description: "Read supplier management module." },
  { key: "expenses.read", module: "expenses", action: "read", description: "Read expenses module." },
  { key: "vendor_quotations.read", module: "vendor_quotations", action: "read", description: "Read vendor quotations." },
  { key: "vendor_quotations.create", module: "vendor_quotations", action: "create", description: "Create vendor quotations." },
  { key: "vendor_quotations.update", module: "vendor_quotations", action: "update", description: "Update vendor quotations." },
  { key: "vendor_quotations.delete", module: "vendor_quotations", action: "delete", description: "Delete vendor quotations." },
  { key: "rate_cards.publish", module: "rate_cards", action: "publish", description: "Publish rate cards." },
];

const moduleActionMap: Record<string, string[]> = {
  service_partners: ["read", "create", "update", "delete"],
  users: ["read", "create", "update", "delete", "status", "roles.assign"],
  roles: ["read", "create", "update", "delete", "assign"],
  permissions: ["read", "assign"],
  clients: ["read", "create", "update", "delete", "export"],
  branches: ["read", "create", "update", "delete", "export"],
  categories: ["read", "create", "update", "delete"],
  items: ["read", "create", "update", "delete"],
  rate_cards: ["read", "create", "update", "delete"],
  service_requests: ["read", "create", "update", "delete", "assign", "status.update", "responsibility.read", "responsibility.update", "timeline", "approve", "export"],
  tasks: ["read", "create", "update", "delete", "assign", "assign.downline", "assign.any", "delegate", "status.update", "remark.create", "history.read", "export"],
  quotations: ["read", "create", "update", "delete", "submit", "approve", "status.update", "export"],
  vendors: ["read", "create", "update", "delete", "export"],
  rfq: ["read", "create", "update", "delete", "send", "status.update", "export"],
  purchase_orders: ["read", "create", "update", "delete", "approve", "send", "status.update", "export"],
  invoices: ["read", "create", "update", "delete", "approve", "send", "status.update", "export"],
  payments: ["read", "create", "update", "delete", "status.update", "export"],
  vendor_payments: ["read", "create", "update", "delete", "status.update", "export"],
  ledger: ["read", "export", "reverse"],
  reports: ["read", "export"],
  activity_logs: ["read", "export", "purge"],
  email_change_requests: ["read", "approve", "reject"],
  notifications: ["read"],
};

function sentenceCase(input: string) {
  return input
    .replaceAll(".", " ")
    .replaceAll("_", " ")
    .split(" ")
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join(" ");
}

function buildModulePermissions(): PermissionDefinition[] {
  return Object.entries(moduleActionMap).flatMap(([module, actions]) =>
    actions.map((action) => ({
      key: `${module}.${action}`,
      module,
      action,
      description: `${sentenceCase(action)} ${sentenceCase(module)}.`,
    }))
  );
}

export const baselinePermissions: PermissionDefinition[] = [...staticPermissions, ...buildModulePermissions()];

export const baselineNavigation: NavigationSeedItem[] = [
  { key: "dashboard", label: "Dashboard", href: "/", sortOrder: 1, permissionKey: "dashboard.read" },
  { key: "users", label: "Client User Management", href: "/users", sortOrder: 2, permissionKey: "users.read" },
  { key: "roles", label: "Roles", href: "/roles", sortOrder: 3, permissionKey: "roles.read" },
  { key: "permissions", label: "Permissions", href: "/permissions", sortOrder: 4, permissionKey: "permissions.read" },
  { key: "service-partners", label: "Service Partners", href: "/service-partners", sortOrder: 5, permissionKey: "service_partners.read" },
  { key: "clients", label: "Clients", href: "/clients", sortOrder: 6, permissionKey: "clients.read" },
  { key: "branches", label: "Branch Management", href: "/branches", sortOrder: 7, permissionKey: "branches.read" },
  { key: "service-requests", label: "Service Requests", href: "/service-requests", sortOrder: 8, permissionKey: "service_requests.read" },
  { key: "categories", label: "Category Management", href: "/categories", sortOrder: 9, permissionKey: "categories.read" },
  { key: "items", label: "Items", href: "/items", sortOrder: 10, permissionKey: "items.read" },
  { key: "rate-cards", label: "RC Management", href: "/rate-cards", sortOrder: 11, permissionKey: "rate_cards.read" },
  { key: "activity-log", label: "Activity Log", href: "/activity-log", sortOrder: 12, permissionKey: "activity_logs.read" },
  { key: "email-change-requests", label: "Email Change Requests", href: "/email-change-requests", sortOrder: 13, permissionKey: "email_change_requests.read" },
  { key: "settings", label: "Settings", href: "/settings", sortOrder: 14, permissionKey: "settings.read" },
  { key: "inventory-management", label: "Inventory Management", href: "#", sortOrder: 20, permissionKey: "inventory.read", isActive: false },
  { key: "supplier-management", label: "Supplier Management", href: "/vendors", sortOrder: 21, permissionKey: "vendors.read", isActive: true },
  { key: "tasks", label: "Tasks", href: "/tasks", sortOrder: 22, permissionKey: "tasks.read", isActive: true },
  { key: "ledger", label: "Ledger", href: "/ledger", sortOrder: 23, permissionKey: "ledger.read", isActive: true },
  { key: "quotations", label: "Quotations", href: "#", sortOrder: 24, permissionKey: "quotations.read", isActive: false },
  { key: "payments", label: "Payments", href: "#", sortOrder: 25, permissionKey: "payments.read", isActive: false },
  { key: "expenses", label: "Expenses", href: "#", sortOrder: 26, permissionKey: "expenses.read", isActive: false },
  { key: "vendor-quotations", label: "Vendors Quotation List", href: "#", sortOrder: 27, permissionKey: "vendor_quotations.read", isActive: false },
  { key: "rfq-list", label: "RFQ List", href: "/rfqs", sortOrder: 28, permissionKey: "rfq.read", isActive: true },
  { key: "po-list", label: "PO List", href: "/purchase-orders", sortOrder: 29, permissionKey: "purchase_orders.read", isActive: true },
  { key: "invoice-list", label: "Invoice List", href: "/invoices", sortOrder: 30, permissionKey: "invoices.read", isActive: true },
  { key: "vendor-payments-list", label: "Vendors Payment List", href: "/vendor-payments", sortOrder: 31, permissionKey: "vendor_payments.read", isActive: true },
  { key: "finance-reports", label: "Finance Reports", href: "/finance-reports", sortOrder: 32, permissionKey: "reports.read", isActive: true },
];

export const baselineRoleDefinitions: RoleSeedDefinition[] = [
  {
    key: "super_admin",
    name: "Super Admin",
    description: "Platform super administrator",
    scope: RoleScope.PLATFORM,
    level: 100,
    isSystem: true,
  },
  {
    key: "company_admin",
    name: "Company Admin",
    description: "Company-wide administrator",
    scope: RoleScope.TENANT,
    level: 90,
    isSystem: true,
  },
  {
    key: "manager",
    name: "Manager",
    description: "Operational manager",
    scope: RoleScope.TENANT,
    level: 70,
    isSystem: true,
  },
  {
    key: "operator",
    name: "Operator",
    description: "Operations user",
    scope: RoleScope.TENANT,
    level: 50,
    isSystem: true,
  },
  {
    key: "technician",
    name: "Technician",
    description: "Field technician",
    scope: RoleScope.TENANT,
    level: 40,
    isSystem: true,
  },
  {
    key: "support",
    name: "Support",
    description: "Support desk user",
    scope: RoleScope.TENANT,
    level: 30,
    isSystem: true,
  },
];

function grantSet(permissionKeys: readonly string[]) {
  return Array.from(new Set(permissionKeys));
}

const commonUserSelfPermissions = ["dashboard.read", "dashboard.company", "profile.email_change.request"] as const;

const companyAdminPermissions = grantSet([
  ...commonUserSelfPermissions,
  "settings.read",
  "settings.update",
  "activity_logs.read",
  "activity_logs.export",
  "users.read",
  "users.create",
  "users.update",
  "users.delete",
  "users.status",
  "users.roles.assign",
  "roles.read",
  "roles.create",
  "roles.update",
  "roles.delete",
  "roles.assign",
  "permissions.read",
  "permissions.assign",
  "clients.read",
  "clients.create",
  "clients.update",
  "clients.delete",
  "clients.export",
  "branches.read",
  "branches.create",
  "branches.update",
  "branches.delete",
  "branches.export",
  "categories.read",
  "categories.create",
  "categories.update",
  "categories.delete",
  "items.read",
  "items.create",
  "items.update",
  "items.delete",
  "rate_cards.read",
  "rate_cards.create",
  "rate_cards.update",
  "rate_cards.delete",
  "rate_cards.publish",
  "service_requests.read",
  "service_requests.create",
  "service_requests.update",
  "service_requests.delete",
  "service_requests.assign",
  "service_requests.responsibility.read",
  "service_requests.responsibility.update",
  "service_requests.timeline",
  "service_requests.status.update",
  "service_requests.export",
  "service_requests.approve",
  "tasks.read",
  "tasks.create",
  "tasks.update",
  "tasks.delete",
  "tasks.assign",
  "tasks.assign.downline",
  "tasks.assign.any",
  "tasks.delegate",
  "tasks.status.update",
  "tasks.remark.create",
  "tasks.history.read",
  "tasks.export",
  "vendors.read",
  "vendors.create",
  "vendors.update",
  "vendors.delete",
  "vendors.export",
  "rfq.read",
  "rfq.create",
  "rfq.update",
  "rfq.delete",
  "rfq.send",
  "rfq.status.update",
  "rfq.export",
  "vendor_quotations.read",
  "vendor_quotations.create",
  "vendor_quotations.update",
  "vendor_quotations.delete",
  "purchase_orders.read",
  "purchase_orders.create",
  "purchase_orders.update",
  "purchase_orders.delete",
  "purchase_orders.approve",
  "purchase_orders.send",
  "purchase_orders.status.update",
  "purchase_orders.export",
  "invoices.read",
  "invoices.create",
  "invoices.update",
  "invoices.delete",
  "invoices.approve",
  "invoices.send",
  "invoices.status.update",
  "invoices.export",
  "ledger.read",
  "ledger.export",
  "payments.read",
  "payments.create",
  "payments.update",
  "payments.delete",
  "payments.status.update",
  "payments.export",
  "vendor_payments.read",
  "vendor_payments.create",
  "vendor_payments.update",
  "vendor_payments.delete",
  "vendor_payments.status.update",
  "vendor_payments.export",
  "reports.read",
  "reports.export",
  "quotations.read",
  "quotations.create",
  "quotations.update",
  "quotations.delete",
  "quotations.submit",
  "quotations.approve",
  "quotations.status.update",
  "quotations.export",
  "notifications.read",
]);

export const rolePermissionGrants: Record<string, readonly string[]> = {
  super_admin: baselinePermissions.map((permission) => permission.key),
  company_admin: companyAdminPermissions,
  manager: grantSet([
    ...commonUserSelfPermissions,
    "settings.read",
    "activity_logs.read",
    "activity_logs.export",
    "users.read",
    "roles.read",
    "permissions.read",
    "clients.read",
    "clients.create",
    "clients.update",
    "clients.export",
    "branches.read",
    "branches.create",
    "branches.update",
    "branches.export",
    "categories.read",
    "items.read",
    "rate_cards.read",
    "service_requests.read",
    "service_requests.create",
    "service_requests.update",
    "service_requests.assign",
    "service_requests.responsibility.read",
    "service_requests.responsibility.update",
    "service_requests.timeline",
    "service_requests.status.update",
    "service_requests.export",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "tasks.assign",
    "tasks.assign.downline",
    "tasks.assign.any",
    "tasks.delegate",
    "tasks.status.update",
    "tasks.remark.create",
    "tasks.history.read",
    "tasks.export",
    "vendors.read",
    "vendors.create",
    "vendors.update",
    "vendors.delete",
    "vendors.export",
    "rfq.read",
    "rfq.create",
    "rfq.update",
    "rfq.delete",
    "rfq.send",
    "rfq.status.update",
    "rfq.export",
    "vendor_quotations.read",
    "vendor_quotations.create",
    "vendor_quotations.update",
    "vendor_quotations.delete",
    "purchase_orders.read",
    "purchase_orders.create",
    "purchase_orders.update",
    "purchase_orders.delete",
    "purchase_orders.approve",
    "purchase_orders.send",
    "purchase_orders.status.update",
    "purchase_orders.export",
    "invoices.read",
    "invoices.create",
    "invoices.update",
    "invoices.delete",
    "invoices.approve",
    "invoices.send",
    "invoices.status.update",
    "invoices.export",
    "ledger.read",
    "ledger.export",
    "payments.read",
    "payments.create",
    "payments.update",
    "payments.delete",
    "payments.status.update",
    "payments.export",
    "vendor_payments.read",
    "vendor_payments.create",
    "vendor_payments.update",
    "vendor_payments.delete",
    "vendor_payments.status.update",
    "vendor_payments.export",
    "reports.read",
    "reports.export",
    "quotations.read",
    "quotations.create",
    "quotations.update",
    "quotations.status.update",
    "quotations.submit",
    "quotations.approve",
    "quotations.export",
    "notifications.read",
  ]),
  operator: grantSet([
    ...commonUserSelfPermissions,
    "clients.read",
    "branches.read",
    "categories.read",
    "items.read",
    "rate_cards.read",
    "service_requests.read",
    "service_requests.create",
    "service_requests.update",
    "service_requests.assign",
    "service_requests.responsibility.read",
    "service_requests.responsibility.update",
    "service_requests.timeline",
    "service_requests.status.update",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "tasks.assign",
    "tasks.assign.downline",
    "tasks.delegate",
    "tasks.status.update",
    "tasks.remark.create",
    "tasks.history.read",
    "vendors.read",
    "vendors.create",
    "vendors.update",
    "rfq.read",
    "rfq.create",
    "rfq.update",
    "rfq.status.update",
    "rfq.send",
    "vendor_quotations.read",
    "vendor_quotations.create",
    "vendor_quotations.update",
    "purchase_orders.read",
    "purchase_orders.create",
    "purchase_orders.update",
    "purchase_orders.status.update",
    "invoices.read",
    "invoices.create",
    "invoices.update",
    "invoices.status.update",
    "invoices.send",
    "ledger.read",
    "payments.read",
    "payments.create",
    "payments.update",
    "payments.status.update",
    "vendor_payments.read",
    "vendor_payments.create",
    "vendor_payments.update",
    "vendor_payments.status.update",
    "reports.read",
    "quotations.read",
    "quotations.create",
    "quotations.update",
    "quotations.status.update",
    "quotations.submit",
  ]),
  technician: grantSet([
    ...commonUserSelfPermissions,
    "clients.read",
    "branches.read",
    "service_requests.read",
    "service_requests.update",
    "service_requests.responsibility.read",
    "service_requests.timeline",
    "service_requests.status.update",
    "tasks.read",
    "tasks.update",
    "tasks.assign",
    "tasks.assign.downline",
    "tasks.delegate",
    "tasks.status.update",
    "tasks.remark.create",
    "tasks.history.read",
    "vendors.read",
    "vendors.create",
    "vendors.update",
    "rfq.read",
    "rfq.create",
    "rfq.update",
    "rfq.status.update",
    "rfq.send",
    "vendor_quotations.read",
    "vendor_quotations.create",
    "vendor_quotations.update",
    "purchase_orders.read",
    "purchase_orders.create",
    "purchase_orders.update",
    "purchase_orders.status.update",
    "invoices.read",
    "invoices.create",
    "invoices.update",
    "invoices.status.update",
    "payments.read",
    "payments.update",
    "payments.status.update",
    "vendor_payments.read",
    "quotations.read",
  ]),
  support: grantSet([
    ...commonUserSelfPermissions,
    "clients.read",
    "branches.read",
    "service_requests.read",
    "service_requests.timeline",
    "activity_logs.read",
    "tasks.read",
    "tasks.history.read",
    "vendors.read",
    "rfq.read",
    "vendor_quotations.read",
    "purchase_orders.read",
    "invoices.read",
    "payments.read",
    "ledger.read",
    "vendor_payments.read",
    "reports.read",
    "quotations.read",
    "notifications.read",
  ]),
};

export const tenantBootstrapRoleKeys = ["company_admin", "manager", "operator", "technician", "support"] as const;

export const baselineSettings: SettingSeedDefinition[] = [
  {
    key: "app.timezone",
    value: { timezone: "Asia/Kolkata" },
    isSecret: false,
  },
  {
    key: "otp.expiry_seconds",
    value: { seconds: 300 },
    isSecret: false,
  },
  {
    key: "otp.max_attempts",
    value: { attempts: 5 },
    isSecret: false,
  },
  {
    key: "otp.resend_cooldown_seconds",
    value: { seconds: 30 },
    isSecret: false,
  },
];
