import { RoleScope } from "@prisma/client";

export type PermissionDefinition = {
  key: string;
  module: string;
  action: string;
  description: string;
};

export type NavigationSeedItem = {
  key: string;
  label: string;
  href: string;
  sortOrder: number;
  permissionKey: string;
  isActive?: boolean;
};

export type RoleSeedDefinition = {
  key: string;
  name: string;
  description: string;
  scope: RoleScope;
  isSystem: boolean;
};

export type SettingSeedDefinition = {
  key: string;
  value: Record<string, unknown>;
  isSecret: boolean;
};

export const baselinePermissions: PermissionDefinition[] = [
  { key: "dashboard.read", module: "dashboard", action: "read", description: "Access dashboard." },
  { key: "dashboard.platform", module: "dashboard", action: "platform", description: "View platform-level dashboard." },
  { key: "dashboard.company", module: "dashboard", action: "company", description: "View company-level dashboard." },
  { key: "platform.dashboard", module: "platform", action: "dashboard", description: "View platform admin dashboard." },
  { key: "platform.manage", module: "platform", action: "manage", description: "Manage platform-level entities." },
  { key: "settings.read", module: "settings", action: "read", description: "Read settings." },
  { key: "settings.update", module: "settings", action: "update", description: "Update settings." },
  { key: "audit_logs.read", module: "audit_logs", action: "read", description: "Read audit logs." },
  { key: "activity_logs.read", module: "activity_logs", action: "read", description: "Read activity logs." },
  { key: "service_partners.read", module: "service_partners", action: "read", description: "Read service partners." },
  { key: "service_partners.create", module: "service_partners", action: "create", description: "Create service partners." },
  { key: "service_partners.update", module: "service_partners", action: "update", description: "Update service partners." },
  { key: "service_partners.delete", module: "service_partners", action: "delete", description: "Delete service partners." },
  { key: "users.read", module: "users", action: "read", description: "Read users." },
  { key: "users.create", module: "users", action: "create", description: "Create users." },
  { key: "users.update", module: "users", action: "update", description: "Update users." },
  { key: "users.delete", module: "users", action: "delete", description: "Delete users." },
  { key: "users.status", module: "users", action: "status", description: "Change user status." },
  { key: "users.roles.assign", module: "users", action: "roles.assign", description: "Assign roles to users." },
  { key: "roles.read", module: "roles", action: "read", description: "Read roles." },
  { key: "roles.create", module: "roles", action: "create", description: "Create roles." },
  { key: "roles.update", module: "roles", action: "update", description: "Update roles." },
  { key: "roles.delete", module: "roles", action: "delete", description: "Delete roles." },
  { key: "roles.assign", module: "roles", action: "assign", description: "Assign role permissions." },
  { key: "permissions.read", module: "permissions", action: "read", description: "Read permissions." },
  { key: "permissions.assign", module: "permissions", action: "assign", description: "Assign permissions." },
  { key: "clients.read", module: "clients", action: "read", description: "Read clients." },
  { key: "clients.create", module: "clients", action: "create", description: "Create clients." },
  { key: "clients.update", module: "clients", action: "update", description: "Update clients." },
  { key: "clients.delete", module: "clients", action: "delete", description: "Delete clients." },
  { key: "branches.read", module: "branches", action: "read", description: "Read branches." },
  { key: "branches.create", module: "branches", action: "create", description: "Create branches." },
  { key: "branches.update", module: "branches", action: "update", description: "Update branches." },
  { key: "branches.delete", module: "branches", action: "delete", description: "Delete branches." },
  { key: "categories.read", module: "categories", action: "read", description: "Read categories." },
  { key: "categories.create", module: "categories", action: "create", description: "Create categories." },
  { key: "categories.update", module: "categories", action: "update", description: "Update categories." },
  { key: "categories.delete", module: "categories", action: "delete", description: "Delete categories." },
  { key: "items.read", module: "items", action: "read", description: "Read items." },
  { key: "items.create", module: "items", action: "create", description: "Create items." },
  { key: "items.update", module: "items", action: "update", description: "Update items." },
  { key: "items.delete", module: "items", action: "delete", description: "Delete items." },
  { key: "rate_cards.read", module: "rate_cards", action: "read", description: "Read rate cards." },
  { key: "rate_cards.create", module: "rate_cards", action: "create", description: "Create rate cards." },
  { key: "rate_cards.update", module: "rate_cards", action: "update", description: "Update rate cards." },
  { key: "rate_cards.delete", module: "rate_cards", action: "delete", description: "Delete rate cards." },
  { key: "rate_cards.publish", module: "rate_cards", action: "publish", description: "Publish rate cards." },
  { key: "service_requests.read", module: "service_requests", action: "read", description: "Read service requests." },
  { key: "service_requests.create", module: "service_requests", action: "create", description: "Create service requests." },
  { key: "service_requests.update", module: "service_requests", action: "update", description: "Update service requests." },
  { key: "service_requests.delete", module: "service_requests", action: "delete", description: "Delete service requests." },
  { key: "service_requests.timeline", module: "service_requests", action: "timeline", description: "View service request timeline." },
  { key: "service_requests.status.change", module: "service_requests", action: "status.change", description: "Change service request status." },
  { key: "service_requests.assign", module: "service_requests", action: "assign", description: "Assign service requests." },
  {
    key: "service_requests.responsibility.read",
    module: "service_requests",
    action: "responsibility.read",
    description: "Read service request responsibility.",
  },
  {
    key: "service_requests.responsibility.update",
    module: "service_requests",
    action: "responsibility.update",
    description: "Update service request responsibility.",
  },
  { key: "service_requests.approve", module: "service_requests", action: "approve", description: "Approve service requests." },
  { key: "inventory.read", module: "inventory", action: "read", description: "Read inventory management module." },
  { key: "inventory.manage", module: "inventory", action: "manage", description: "Manage inventory module." },
  { key: "suppliers.read", module: "suppliers", action: "read", description: "Read supplier management module." },
  { key: "vendors.read", module: "vendors", action: "read", description: "Read vendors." },
  { key: "vendors.create", module: "vendors", action: "create", description: "Create vendors." },
  { key: "vendors.update", module: "vendors", action: "update", description: "Update vendors." },
  { key: "vendors.delete", module: "vendors", action: "delete", description: "Delete vendors." },
  { key: "tasks.read", module: "tasks", action: "read", description: "Read tasks module." },
  { key: "tasks.create", module: "tasks", action: "create", description: "Create tasks." },
  { key: "tasks.update", module: "tasks", action: "update", description: "Update tasks." },
  { key: "tasks.delete", module: "tasks", action: "delete", description: "Delete tasks." },
  { key: "tasks.status.update", module: "tasks", action: "status.update", description: "Update task status." },
  { key: "ledger.read", module: "ledger", action: "read", description: "Read ledger module." },
  { key: "quotations.read", module: "quotations", action: "read", description: "Read quotations module." },
  { key: "quotations.create", module: "quotations", action: "create", description: "Create quotations." },
  { key: "quotations.update", module: "quotations", action: "update", description: "Update quotations." },
  { key: "quotations.delete", module: "quotations", action: "delete", description: "Delete quotations." },
  { key: "quotations.status.update", module: "quotations", action: "status.update", description: "Update quotation status." },
  { key: "quotations.submit", module: "quotations", action: "submit", description: "Submit quotations." },
  { key: "quotations.approve", module: "quotations", action: "approve", description: "Approve quotations." },
  { key: "payments.read", module: "payments", action: "read", description: "Read payments module." },
  { key: "payments.create", module: "payments", action: "create", description: "Create payments." },
  { key: "payments.update", module: "payments", action: "update", description: "Update payments." },
  { key: "payments.delete", module: "payments", action: "delete", description: "Delete payments." },
  { key: "payments.status.update", module: "payments", action: "status.update", description: "Update payment status." },
  { key: "expenses.read", module: "expenses", action: "read", description: "Read expenses module." },
  { key: "vendor_quotations.read", module: "vendor_quotations", action: "read", description: "Read vendor quotation list module." },
  { key: "vendor_quotations.create", module: "vendor_quotations", action: "create", description: "Create vendor quotations." },
  { key: "vendor_quotations.update", module: "vendor_quotations", action: "update", description: "Update vendor quotations." },
  { key: "vendor_quotations.delete", module: "vendor_quotations", action: "delete", description: "Delete vendor quotations." },
  { key: "rfq.read", module: "rfq", action: "read", description: "Read RFQ module." },
  { key: "rfq.create", module: "rfq", action: "create", description: "Create RFQs." },
  { key: "rfq.update", module: "rfq", action: "update", description: "Update RFQs." },
  { key: "rfq.delete", module: "rfq", action: "delete", description: "Delete RFQs." },
  { key: "rfq.status.update", module: "rfq", action: "status.update", description: "Update RFQ status." },
  { key: "rfq.send", module: "rfq", action: "send", description: "Send or publish RFQs to vendors." },
  { key: "purchase_orders.read", module: "purchase_orders", action: "read", description: "Read purchase orders module." },
  { key: "purchase_orders.create", module: "purchase_orders", action: "create", description: "Create purchase orders." },
  { key: "purchase_orders.update", module: "purchase_orders", action: "update", description: "Update purchase orders." },
  { key: "purchase_orders.delete", module: "purchase_orders", action: "delete", description: "Delete purchase orders." },
  {
    key: "purchase_orders.status.update",
    module: "purchase_orders",
    action: "status.update",
    description: "Update purchase order status.",
  },
  { key: "invoices.read", module: "invoices", action: "read", description: "Read invoices module." },
  { key: "invoices.create", module: "invoices", action: "create", description: "Create invoices." },
  { key: "invoices.update", module: "invoices", action: "update", description: "Update invoices." },
  { key: "invoices.delete", module: "invoices", action: "delete", description: "Delete invoices." },
  { key: "invoices.status.update", module: "invoices", action: "status.update", description: "Update invoice status." },
  { key: "invoices.send", module: "invoices", action: "send", description: "Send invoices." },
  { key: "invoices.approve", module: "invoices", action: "approve", description: "Approve invoices." },
  { key: "vendor_payments.read", module: "vendor_payments", action: "read", description: "Read vendor payments module." },
  { key: "reports.read", module: "reports", action: "read", description: "Read reports." },
];

export const baselineNavigation: NavigationSeedItem[] = [
  { key: "dashboard", label: "Dashboard", href: "/", sortOrder: 1, permissionKey: "dashboard.read" },
  { key: "users", label: "Client User Management", href: "/users", sortOrder: 2, permissionKey: "users.read" },
  { key: "roles", label: "Roles", href: "/roles", sortOrder: 3, permissionKey: "roles.read" },
  { key: "permissions", label: "Permissions", href: "/permissions", sortOrder: 4, permissionKey: "permissions.read" },
  { key: "service-partners", label: "Service Partners", href: "/service-partners", sortOrder: 5, permissionKey: "service_partners.read" },
  { key: "clients", label: "Clients", href: "/clients", sortOrder: 6, permissionKey: "clients.read" },
  { key: "branches", label: "Branch Management", href: "/branches", sortOrder: 7, permissionKey: "branches.read" },
  { key: "service-requests", label: "Service Requests", href: "/service-requests", sortOrder: 8, permissionKey: "service_requests.read" },
  { key: "categories", label: "Category Management", href: "/categories", sortOrder: 9, permissionKey: "categories.read" },
  { key: "items", label: "Items", href: "/items", sortOrder: 10, permissionKey: "items.read" },
  { key: "rate-cards", label: "RC Management", href: "/rate-cards", sortOrder: 11, permissionKey: "rate_cards.read" },
  { key: "activity-log", label: "Activity Log", href: "/activity-log", sortOrder: 12, permissionKey: "activity_logs.read" },
  { key: "settings", label: "Settings", href: "/settings", sortOrder: 13, permissionKey: "settings.read" },
  { key: "inventory-management", label: "Inventory Management", href: "#", sortOrder: 20, permissionKey: "inventory.read", isActive: false },
  { key: "supplier-management", label: "Supplier Management", href: "/vendors", sortOrder: 21, permissionKey: "vendors.read", isActive: true },
  { key: "tasks", label: "Tasks", href: "#", sortOrder: 22, permissionKey: "tasks.read", isActive: false },
  { key: "ledger", label: "Ledger", href: "/ledger", sortOrder: 23, permissionKey: "ledger.read", isActive: true },
  { key: "quotations", label: "Quotations", href: "#", sortOrder: 24, permissionKey: "quotations.read", isActive: false },
  { key: "payments", label: "Payments", href: "#", sortOrder: 25, permissionKey: "payments.read", isActive: false },
  { key: "expenses", label: "Expenses", href: "#", sortOrder: 26, permissionKey: "expenses.read", isActive: false },
  { key: "vendor-quotations", label: "Vendors Quotation List", href: "#", sortOrder: 27, permissionKey: "vendor_quotations.read", isActive: false },
  { key: "rfq-list", label: "RFQ List", href: "/rfqs", sortOrder: 28, permissionKey: "rfq.read", isActive: true },
  { key: "po-list", label: "PO List", href: "/purchase-orders", sortOrder: 29, permissionKey: "purchase_orders.read", isActive: true },
  { key: "invoice-list", label: "Invoice List", href: "/invoices", sortOrder: 30, permissionKey: "invoices.read", isActive: true },
  { key: "vendor-payments-list", label: "Vendors Payment List", href: "#", sortOrder: 31, permissionKey: "vendor_payments.read", isActive: false },
];

export const baselineRoleDefinitions: RoleSeedDefinition[] = [
  {
    key: "super_admin",
    name: "Super Admin",
    description: "Platform super administrator",
    scope: RoleScope.PLATFORM,
    isSystem: true,
  },
  {
    key: "company_admin",
    name: "Company Admin",
    description: "Company-wide administrator",
    scope: RoleScope.TENANT,
    isSystem: true,
  },
  {
    key: "manager",
    name: "Manager",
    description: "Operational manager",
    scope: RoleScope.TENANT,
    isSystem: true,
  },
  {
    key: "operator",
    name: "Operator",
    description: "Operations user",
    scope: RoleScope.TENANT,
    isSystem: true,
  },
  {
    key: "technician",
    name: "Technician",
    description: "Field technician",
    scope: RoleScope.TENANT,
    isSystem: true,
  },
  {
    key: "support",
    name: "Support",
    description: "Support desk user",
    scope: RoleScope.TENANT,
    isSystem: true,
  },
];

const companyAdminPermissions = [
  "dashboard.read",
  "dashboard.company",
  "settings.read",
  "settings.update",
  "activity_logs.read",
  "users.read",
  "users.create",
  "users.update",
  "users.delete",
  "users.status",
  "users.roles.assign",
  "roles.read",
  "roles.create",
  "roles.update",
  "roles.delete",
  "roles.assign",
  "permissions.read",
  "permissions.assign",
  "clients.read",
  "clients.create",
  "clients.update",
  "clients.delete",
  "branches.read",
  "branches.create",
  "branches.update",
  "branches.delete",
  "categories.read",
  "categories.create",
  "categories.update",
  "categories.delete",
  "items.read",
  "items.create",
  "items.update",
  "items.delete",
  "rate_cards.read",
  "rate_cards.create",
  "rate_cards.update",
  "rate_cards.delete",
  "rate_cards.publish",
  "service_requests.read",
  "service_requests.create",
  "service_requests.update",
  "service_requests.delete",
  "service_requests.responsibility.read",
  "service_requests.responsibility.update",
  "service_requests.timeline",
  "service_requests.status.change",
  "tasks.read",
  "tasks.create",
  "tasks.update",
  "tasks.delete",
  "tasks.status.update",
  "vendors.read",
  "vendors.create",
  "vendors.update",
  "vendors.delete",
  "rfq.read",
  "rfq.create",
  "rfq.update",
  "rfq.delete",
  "rfq.status.update",
  "rfq.send",
  "vendor_quotations.read",
  "vendor_quotations.create",
  "vendor_quotations.update",
  "vendor_quotations.delete",
  "purchase_orders.read",
  "purchase_orders.create",
  "purchase_orders.update",
  "purchase_orders.delete",
  "purchase_orders.status.update",
  "invoices.read",
  "invoices.create",
  "invoices.update",
  "invoices.delete",
  "invoices.status.update",
  "invoices.send",
  "invoices.approve",
  "ledger.read",
  "payments.read",
  "payments.create",
  "payments.update",
  "payments.delete",
  "payments.status.update",
  "quotations.read",
  "quotations.create",
  "quotations.update",
  "quotations.delete",
  "quotations.status.update",
  "quotations.submit",
  "quotations.approve",
] as const;

export const rolePermissionGrants: Record<string, readonly string[]> = {
  super_admin: baselinePermissions.map((permission) => permission.key),
  company_admin: companyAdminPermissions,
  manager: [
    "dashboard.read",
    "dashboard.company",
    "settings.read",
    "users.read",
    "roles.read",
    "permissions.read",
    "clients.read",
    "clients.create",
    "clients.update",
    "branches.read",
    "branches.create",
    "branches.update",
    "categories.read",
    "items.read",
    "rate_cards.read",
    "service_requests.read",
    "service_requests.create",
    "service_requests.update",
    "service_requests.responsibility.read",
    "service_requests.responsibility.update",
    "service_requests.timeline",
    "service_requests.status.change",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "tasks.status.update",
    "vendors.read",
    "vendors.create",
    "vendors.update",
    "vendors.delete",
    "rfq.read",
    "rfq.create",
    "rfq.update",
    "rfq.delete",
    "rfq.status.update",
    "rfq.send",
    "vendor_quotations.read",
    "vendor_quotations.create",
    "vendor_quotations.update",
    "vendor_quotations.delete",
    "purchase_orders.read",
    "purchase_orders.create",
    "purchase_orders.update",
    "purchase_orders.delete",
    "purchase_orders.status.update",
    "invoices.read",
    "invoices.create",
    "invoices.update",
    "invoices.delete",
    "invoices.status.update",
    "invoices.send",
    "invoices.approve",
    "ledger.read",
    "payments.read",
    "payments.create",
    "payments.update",
    "payments.delete",
    "payments.status.update",
    "quotations.read",
    "quotations.create",
    "quotations.update",
    "quotations.status.update",
    "quotations.submit",
    "quotations.approve",
    "activity_logs.read",
  ],
  operator: [
    "dashboard.read",
    "dashboard.company",
    "clients.read",
    "branches.read",
    "categories.read",
    "items.read",
    "rate_cards.read",
    "service_requests.read",
    "service_requests.create",
    "service_requests.update",
    "service_requests.responsibility.read",
    "service_requests.responsibility.update",
    "service_requests.timeline",
    "service_requests.status.change",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "tasks.status.update",
    "vendors.read",
    "vendors.create",
    "vendors.update",
    "rfq.read",
    "rfq.create",
    "rfq.update",
    "rfq.status.update",
    "rfq.send",
    "vendor_quotations.read",
    "vendor_quotations.create",
    "vendor_quotations.update",
    "purchase_orders.read",
    "purchase_orders.create",
    "purchase_orders.update",
    "purchase_orders.status.update",
    "invoices.read",
    "invoices.create",
    "invoices.update",
    "invoices.status.update",
    "invoices.send",
    "ledger.read",
    "payments.read",
    "payments.create",
    "payments.update",
    "payments.status.update",
    "quotations.read",
    "quotations.create",
    "quotations.update",
    "quotations.status.update",
    "quotations.submit",
  ],
  technician: [
    "dashboard.read",
    "dashboard.company",
    "clients.read",
    "branches.read",
    "service_requests.read",
    "service_requests.update",
    "service_requests.responsibility.read",
    "service_requests.timeline",
    "service_requests.status.change",
    "tasks.read",
    "tasks.update",
    "tasks.status.update",
    "vendors.read",
    "vendors.create",
    "vendors.update",
    "rfq.read",
    "rfq.create",
    "rfq.update",
    "rfq.status.update",
    "rfq.send",
    "vendor_quotations.read",
    "vendor_quotations.create",
    "vendor_quotations.update",
    "purchase_orders.read",
    "purchase_orders.create",
    "purchase_orders.update",
    "purchase_orders.status.update",
    "invoices.read",
    "invoices.create",
    "invoices.update",
    "invoices.status.update",
    "payments.read",
    "payments.update",
    "payments.status.update",
    "quotations.read",
  ],
  support: [
    "dashboard.read",
    "dashboard.company",
    "clients.read",
    "branches.read",
    "service_requests.read",
    "service_requests.timeline",
    "activity_logs.read",
    "tasks.read",
    "vendors.read",
    "rfq.read",
    "vendor_quotations.read",
    "purchase_orders.read",
    "invoices.read",
    "payments.read",
    "ledger.read",
    "quotations.read",
  ],
};

export const tenantBootstrapRoleKeys = ["company_admin", "manager", "operator", "technician", "support"] as const;

export const baselineSettings: SettingSeedDefinition[] = [
  {
    key: "app.timezone",
    value: { timezone: "Asia/Kolkata" },
    isSecret: false,
  },
  {
    key: "otp.expiry_seconds",
    value: { seconds: 300 },
    isSecret: false,
  },
  {
    key: "otp.max_attempts",
    value: { attempts: 5 },
    isSecret: false,
  },
  {
    key: "otp.resend_cooldown_seconds",
    value: { seconds: 30 },
    isSecret: false,
  },
];
