export type IndiaStateReference = {
  name: string;
  code: string;
  cities: string[];
};

function createStateReference(name: string, code: string, cities: string[]): IndiaStateReference {
  const seen = new Set<string>();
  const normalizedCities = cities
    .map((city) => city.trim())
    .filter((city) => {
      if (!city) {
        return false;
      }

      const key = city.toLowerCase();
      if (seen.has(key)) {
        return false;
      }

      seen.add(key);
      return true;
    });

  return {
    name,
    code,
    cities: normalizedCities,
  };
}

// Curated reference data for common Indian district headquarters, cities, and towns.
// If the product later needs a fully authoritative master, this file can be replaced by an external import pipeline.
export const indiaStateReferences: IndiaStateReference[] = [
  createStateReference("Andaman and Nicobar Islands", "AN", [
    "Port Blair",
    "Diglipur",
    "Rangat",
    "Mayabunder",
    "Garacharma",
    "Hut Bay",
    "Campbell Bay",
    "Car Nicobar",
  ]),
  createStateReference("Andhra Pradesh", "AP", [
    "Visakhapatnam",
    "Vijayawada",
    "Tirupati",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Rajahmundry",
    "Kakinada",
    "Kadapa",
    "Anantapur",
    "Eluru",
    "Ongole",
    "Chittoor",
    "Machilipatnam",
    "Srikakulam",
    "Vizianagaram",
    "Tenali",
    "Hindupur",
    "Adoni",
    "Bhimavaram",
    "Tadepalligudem",
    "Nandyal",
  ]),
  createStateReference("Arunachal Pradesh", "AR", [
    "Itanagar",
    "Naharlagun",
    "Tawang",
    "Pasighat",
    "Ziro",
    "Bomdila",
    "Aalo",
    "Tezu",
    "Roing",
    "Seppa",
    "Daporijo",
    "Khonsa",
  ]),
  createStateReference("Assam", "AS", [
    "Guwahati",
    "Dibrugarh",
    "Silchar",
    "Jorhat",
    "Nagaon",
    "Tinsukia",
    "Tezpur",
    "Bongaigaon",
    "Diphu",
    "Sivasagar",
    "Goalpara",
    "Dhubri",
    "Barpeta",
    "Karimganj",
    "North Lakhimpur",
  ]),
  createStateReference("Bihar", "BR", [
    "Patna",
    "Gaya",
    "Muzaffarpur",
    "Bhagalpur",
    "Darbhanga",
    "Purnia",
    "Bihar Sharif",
    "Ara",
    "Begusarai",
    "Katihar",
    "Munger",
    "Chapra",
    "Sasaram",
    "Bettiah",
    "Hajipur",
    "Samastipur",
    "Siwan",
    "Motihari",
    "Madhubani",
    "Sitamarhi",
    "Kishanganj",
  ]),
  createStateReference("Chandigarh", "CH", [
    "Chandigarh",
    "Manimajra",
  ]),
  createStateReference("Chhattisgarh", "CG", [
    "Raipur",
    "Bilaspur",
    "Durg",
    "Bhilai",
    "Korba",
    "Raigarh",
    "Jagdalpur",
    "Ambikapur",
    "Rajnandgaon",
    "Dhamtari",
    "Janjgir",
    "Mahasamund",
    "Kanker",
    "Kawardha",
  ]),
  createStateReference("Dadra and Nagar Haveli and Daman and Diu", "DH", [
    "Daman",
    "Diu",
    "Silvassa",
    "Dadra",
    "Naroli",
    "Moti Daman",
    "Nani Daman",
  ]),
  createStateReference("Delhi", "DL", [
    "New Delhi",
    "Delhi",
    "Dwarka",
    "Rohini",
    "Saket",
    "Karol Bagh",
    "Janakpuri",
    "Pitampura",
    "Shahdara",
    "Najafgarh",
    "Narela",
    "Alipur",
    "Lajpat Nagar",
    "Mayur Vihar",
  ]),
  createStateReference("Goa", "GA", [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Cuncolim",
    "Sanquelim",
    "Quepem",
    "Valpoi",
  ]),
  createStateReference("Gujarat", "GJ", [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Anand",
    "Nadiad",
    "Morbi",
    "Mehsana",
    "Bharuch",
    "Porbandar",
    "Vapi",
    "Navsari",
    "Surendranagar",
    "Bhuj",
    "Veraval",
    "Godhra",
    "Palanpur",
    "Dahod",
  ]),
  createStateReference("Haryana", "HR", [
    "Gurugram",
    "Faridabad",
    "Panipat",
    "Ambala",
    "Karnal",
    "Hisar",
    "Rohtak",
    "Sonipat",
    "Yamunanagar",
    "Panchkula",
    "Bhiwani",
    "Rewari",
    "Sirsa",
    "Bahadurgarh",
    "Jind",
    "Kaithal",
    "Kurukshetra",
    "Narnaul",
    "Palwal",
    "Fatehabad",
  ]),
  createStateReference("Himachal Pradesh", "HP", [
    "Shimla",
    "Dharamshala",
    "Solan",
    "Mandi",
    "Kullu",
    "Hamirpur",
    "Una",
    "Chamba",
    "Nahan",
    "Bilaspur",
    "Kangra",
    "Manali",
    "Palampur",
    "Baddi",
  ]),
  createStateReference("Jammu and Kashmir", "JK", [
    "Srinagar",
    "Jammu",
    "Anantnag",
    "Baramulla",
    "Sopore",
    "Kathua",
    "Udhampur",
    "Kupwara",
    "Pulwama",
    "Poonch",
    "Rajouri",
    "Kulgam",
    "Budgam",
    "Bandipora",
  ]),
  createStateReference("Jharkhand", "JH", [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Deoghar",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Medininagar",
    "Chaibasa",
    "Dumka",
    "Sahibganj",
    "Gumla",
    "Lohardaga",
    "Pakur",
  ]),
  createStateReference("Karnataka", "KA", [
    "Bengaluru",
    "Mysuru",
    "Mangaluru",
    "Hubballi",
    "Belagavi",
    "Davanagere",
    "Ballari",
    "Shivamogga",
    "Tumakuru",
    "Udupi",
    "Vijayapura",
    "Hassan",
    "Raichur",
    "Kalaburagi",
    "Bidar",
    "Chitradurga",
    "Kolar",
    "Mandya",
    "Bagalkot",
    "Karwar",
    "Chikkamagaluru",
    "Gadag",
  ]),
  createStateReference("Kerala", "KL", [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Kannur",
    "Alappuzha",
    "Palakkad",
    "Malappuram",
    "Kottayam",
    "Kasaragod",
    "Pathanamthitta",
    "Idukki",
    "Wayanad",
  ]),
  createStateReference("Ladakh", "LA", [
    "Leh",
    "Kargil",
    "Diskit",
    "Nyoma",
  ]),
  createStateReference("Lakshadweep", "LD", [
    "Kavaratti",
    "Agatti",
    "Minicoy",
    "Andrott",
    "Amini",
  ]),
  createStateReference("Madhya Pradesh", "MP", [
    "Bhopal",
    "Indore",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Satna",
    "Rewa",
    "Ratlam",
    "Dewas",
    "Burhanpur",
    "Chhindwara",
    "Katni",
    "Singrauli",
    "Vidisha",
    "Morena",
    "Sehore",
    "Shivpuri",
    "Mandsaur",
    "Neemuch",
    "Betul",
    "Narmadapuram",
  ]),
  createStateReference("Maharashtra", "MH", [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Thane",
    "Navi Mumbai",
    "Aurangabad",
    "Kolhapur",
    "Solapur",
    "Amravati",
    "Nanded",
    "Jalgaon",
    "Akola",
    "Latur",
    "Ahmednagar",
    "Chandrapur",
    "Sangli",
    "Satara",
    "Dhule",
    "Bhiwandi",
    "Ulhasnagar",
    "Malegaon",
    "Ratnagiri",
    "Wardha",
    "Yavatmal",
  ]),
  createStateReference("Manipur", "MN", [
    "Imphal",
    "Thoubal",
    "Bishnupur",
    "Churachandpur",
    "Kakching",
    "Senapati",
    "Ukhrul",
    "Tamenglong",
    "Jiribam",
    "Moreh",
  ]),
  createStateReference("Meghalaya", "ML", [
    "Shillong",
    "Tura",
    "Jowai",
    "Nongpoh",
    "Williamnagar",
    "Baghmara",
    "Nongstoin",
    "Resubelpara",
    "Mairang",
    "Ampati",
  ]),
  createStateReference("Mizoram", "MZ", [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Kolasib",
    "Serchhip",
    "Saiha",
    "Lawngtlai",
    "Mamit",
    "Saitual",
    "Khawzawl",
  ]),
  createStateReference("Nagaland", "NL", [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Wokha",
    "Tuensang",
    "Mon",
    "Zunheboto",
    "Phek",
    "Kiphire",
    "Longleng",
  ]),
  createStateReference("Odisha", "OD", [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Berhampur",
    "Sambalpur",
    "Puri",
    "Balasore",
    "Bhadrak",
    "Baripada",
    "Jharsuguda",
    "Jeypore",
    "Angul",
    "Balangir",
    "Bargarh",
    "Dhenkanal",
    "Kendrapara",
    "Koraput",
    "Paradip",
  ]),
  createStateReference("Puducherry", "PY", [
    "Puducherry",
    "Karaikal",
    "Yanam",
    "Mahe",
    "Oulgaret",
  ]),
  createStateReference("Punjab", "PB", [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
    "Hoshiarpur",
    "Pathankot",
    "Moga",
    "Batala",
    "Abohar",
    "Malerkotla",
    "Barnala",
    "Firozpur",
    "Kapurthala",
    "Sangrur",
    "Faridkot",
    "Sri Muktsar Sahib",
    "Khanna",
  ]),
  createStateReference("Rajasthan", "RJ", [
    "Jaipur",
    "Jodhpur",
    "Udaipur",
    "Kota",
    "Ajmer",
    "Bikaner",
    "Alwar",
    "Bharatpur",
    "Sikar",
    "Pali",
    "Bhilwara",
    "Sri Ganganagar",
    "Hanumangarh",
    "Churu",
    "Jhunjhunu",
    "Barmer",
    "Jaisalmer",
    "Tonk",
    "Sawai Madhopur",
    "Nagaur",
    "Banswara",
    "Dungarpur",
  ]),
  createStateReference("Sikkim", "SK", [
    "Gangtok",
    "Namchi",
    "Gyalshing",
    "Mangan",
    "Rangpo",
    "Singtam",
    "Jorethang",
    "Ravangla",
    "Pakyong",
    "Soreng",
  ]),
  createStateReference("Tamil Nadu", "TN", [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Erode",
    "Vellore",
    "Thoothukudi",
    "Dindigul",
    "Thanjavur",
    "Nagercoil",
    "Hosur",
    "Karur",
    "Tiruppur",
    "Cuddalore",
    "Kanchipuram",
    "Nagapattinam",
    "Sivakasi",
    "Pollachi",
    "Pudukkottai",
    "Ramanathapuram",
    "Namakkal",
    "Dharmapuri",
  ]),
  createStateReference("Telangana", "TS", [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Ramagundam",
    "Mahbubnagar",
    "Nalgonda",
    "Adilabad",
    "Siddipet",
    "Suryapet",
    "Jagtial",
    "Sangareddy",
    "Medak",
    "Miryalaguda",
    "Kamareddy",
    "Mancherial",
  ]),
  createStateReference("Tripura", "TR", [
    "Agartala",
    "Udaipur",
    "Dharmanagar",
    "Kailashahar",
    "Belonia",
    "Ambassa",
    "Khowai",
    "Sabroom",
    "Teliamura",
    "Bishramganj",
  ]),
  createStateReference("Uttar Pradesh", "UP", [
    "Lucknow",
    "Noida",
    "Kanpur",
    "Varanasi",
    "Agra",
    "Prayagraj",
    "Ghaziabad",
    "Meerut",
    "Gorakhpur",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Jhansi",
    "Saharanpur",
    "Mathura",
    "Ayodhya",
    "Muzaffarnagar",
    "Firozabad",
    "Rae Bareli",
    "Shahjahanpur",
    "Rampur",
    "Basti",
    "Sultanpur",
    "Unnao",
    "Etawah",
    "Sitapur",
  ]),
  createStateReference("Uttarakhand", "UK", [
    "Dehradun",
    "Haridwar",
    "Haldwani",
    "Rudrapur",
    "Roorkee",
    "Kashipur",
    "Nainital",
    "Rishikesh",
    "Almora",
    "Pithoragarh",
    "Kotdwar",
    "Tehri",
    "Uttarkashi",
    "Chamoli",
  ]),
  createStateReference("West Bengal", "WB", [
    "Kolkata",
    "Howrah",
    "Siliguri",
    "Durgapur",
    "Asansol",
    "Malda",
    "Kharagpur",
    "Haldia",
    "Bardhaman",
    "Baharampur",
    "Jalpaiguri",
    "Raiganj",
    "Cooch Behar",
    "Bankura",
    "Purulia",
    "Krishnanagar",
    "Serampore",
    "Darjeeling",
    "Balurghat",
    "Tamluk",
  ]),
];
